name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 4.2
          - django-version: "4.2.0"
            python-version: "3.10"
          - django-version: "4.2.0"
            python-version: "3.11"
          - django-version: "4.2.0"
            python-version: "3.12"
          - django-version: "4.2.0"
            python-version: "3.13"
          # Django 5.0
          - django-version: "5.0.0"
            python-version: "3.10"
          - django-version: "5.0.0"
            python-version: "3.11"
          - django-version: "5.0.0"
            python-version: "3.12"
          - django-version: "5.0.0"
            python-version: "3.13"
          # Django 5.1
          - django-version: "5.1.0"
            python-version: "3.10"
          - django-version: "5.1.0"
            python-version: "3.11"
          - django-version: "5.1.0"
            python-version: "3.12"
          - django-version: "5.1.0"
            python-version: "3.13"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: python -m pip install -U pip

      - name: Install django version and install dependencies
        run: python -m pip install "Django~=${{ matrix.django-version }}" -e . -r tests/requirements.txt

      - name: Run Tests
        run: |
          make test
